# Generated by Django 2.0.6 on 2018-06-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcodes.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=1000)),
                ('vote', models.IntegerField(default=3)),
                ('comment', models.CharField(max_length=10000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcodes.Doctor')),
            ],
        ),
    ]
