# Generated by Django 2.0.6 on 2018-06-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinic',
            field=models.CharField(default='Поликлиника', max_length=1000),
        ),
    ]
